include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    type_annotate_public_apis: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
