import 'package:flutter/material.dart'
    show
        Color,
        Colors,
        Curves,
        EdgeInsets,
        FontWeight,
        LinearGradient,
        MainAxisAlignment,
        TextAlign,
        TextStyle;
import 'package:flutter/widgets.dart' show CrossAxisAlignment;
import 'package:flutter_lyric/core/lyric_style.dart';

abstract class LyricStyles {
  static final default1 = LyricStyle(
    textStyle: TextStyle(fontSize: 14, color: Colors.white70),
    activeStyle: TextStyle(fontSize: 16, color: Colors.white),
    translationStyle: TextStyle(fontSize: 12, color: Colors.white70),
    lineTextAlign: TextAlign.center,
    lineGap: 26,
    translationLineGap: 10,
    contentAlignment: CrossAxisAlignment.center,
    contentPadding: EdgeInsets.only(top: 500, left: 20, right: 20, bottom: 20),
    selectionAnchorPosition: 0.48,
    fadeRange: FadeRange(top: 80, bottom: 80),
    selectedColor: Colors.white,
    selectedTranslationColor: Colors.white,
    scrollDuration: Duration(milliseconds: 240),
    scrollDurations: {
      500: Duration(milliseconds: 500),
      1000: Duration(milliseconds: 1000),
    },
    enableSwitchAnimation: false,
    selectionAutoResumeMode: SelectionAutoResumeMode.selecting,
    selectionAutoResumeDuration: Duration(milliseconds: 320),
    activeAutoResumeDuration: Duration(milliseconds: 3000),
    activeHighlightColor: Colors.yellow,
    switchEnterDuration: Duration(milliseconds: 300),
    switchExitDuration: Duration(milliseconds: 500),
    switchEnterCurve: Curves.easeOutBack,
    switchExitCurve: Curves.easeOutQuint,
    selectionAlignment: MainAxisAlignment.center,
  );

  static final default2 = LyricStyle(
    textStyle: TextStyle(fontSize: 12, color: Colors.white70, height: 1.2),
    activeStyle: TextStyle(
      fontSize: 18,
      height: 1.2,
      color: Colors.white,
      fontWeight: FontWeight.w600,
    ),
    translationStyle: TextStyle(fontSize: 12, color: Colors.white70),
    translationActiveColor: Colors.white,
    lineTextAlign: TextAlign.left,
    lineGap: 20,
    translationLineGap: 5,
    contentAlignment: CrossAxisAlignment.start,
    contentPadding: EdgeInsets.only(top: 40, left: 20, right: 20, bottom: 20),
    selectionAnchorPosition: 0.5,
    activeAnchorPosition: 100,
    fadeRange: FadeRange(top: 40, bottom: 80),
    selectionAlignment: MainAxisAlignment.end,
    activeAlignment: MainAxisAlignment.start,
    selectedColor: Colors.white,
    selectedTranslationColor: Colors.white,
    scrollDuration: Duration(milliseconds: 240),
    scrollDurations: {
      500: Duration(milliseconds: 500),
      1000: Duration(milliseconds: 1000),
    },
    enableSwitchAnimation: true,
    selectionAutoResumeMode: SelectionAutoResumeMode.neverResume,
    selectionAutoResumeDuration: Duration(milliseconds: 320),
    activeAutoResumeDuration: Duration(milliseconds: 2000),
    switchEnterDuration: Duration(milliseconds: 500),
    switchExitDuration: Duration(milliseconds: 500),
    switchEnterCurve: Curves.easeIn,
    switchExitCurve: Curves.easeOut,
    activeHighlightGradient: LinearGradient(
      colors: [
        Color(0xFF3bb2b8),
        Color(0xFF42e695),
      ],
    ),
    activeHighlightExtraFadeWidth: 40,
  );
  static final single = LyricStyle(
    textStyle: TextStyle(fontSize: 14, color: Colors.white70, height: 1.2),
    activeStyle: TextStyle(
      fontSize: 24,
      height: 1.2,
      color: Colors.white,
      fontWeight: FontWeight.w600,
    ),
    translationStyle: TextStyle(fontSize: 12, color: Colors.white70),
    translationActiveColor: Colors.white,
    lineTextAlign: TextAlign.center,
    lineGap: 0,
    translationLineGap: 10,
    activeLineOnly: true,
    disableTouchEvent: true,
    contentAlignment: CrossAxisAlignment.center,
    selectionAnchorPosition: 0.5,
    contentPadding: EdgeInsets.only(top: 800, left: 20, right: 20),
    fadeRange: FadeRange(top: 0, bottom: 0),
    selectionAlignment: MainAxisAlignment.center,
    activeAlignment: MainAxisAlignment.center,
    selectedColor: Colors.white,
    selectedTranslationColor: Colors.white,
    scrollDuration: Duration(milliseconds: 0),
    enableSwitchAnimation: false,
    selectionAutoResumeMode: SelectionAutoResumeMode.neverResume,
    selectionAutoResumeDuration: Duration(milliseconds: 320),
    activeAutoResumeDuration: Duration(milliseconds: 3000),
    activeHighlightColor: const Color.fromARGB(255, 120, 255, 124),
    switchEnterDuration: Duration(milliseconds: 500),
    switchExitDuration: Duration(milliseconds: 500),
    switchEnterCurve: Curves.easeIn,
    switchExitCurve: Curves.easeOut,
    activeHighlightExtraFadeWidth: 40,
  );
}
